In [1]:
import pandas as pd
df=pd.read_csv('mid.csv')
df.head()

0  \
0      Woman in a black dress walking on the street.   
1           A man and a woman looking at the camera.   
2  a brown dog running through the dirty muddy grass   
3  Three dogs pulling a man on a bicycle through ...   
4  A baby in a red hat sitting in a stroller is h...   

                                                   1     2  \
0        A woman watches a dog jump down the stairs.  0.80   
1                        A man and a woman laughing.  2.33   
2  The large brown dog is running outside in the ...  3.60   
3  The dogs are pulling a man on a type of bike, ...  5.00   
4  A man in a gray shirt sitting in a field of fl...  0.00   

                                                   4  \
0  ['एक महिला एक कुत्ता को सीढ़ियों से नीचे उछलने...   
1                 ['एक आदमी और एक औरत हंस रहे हैं।']   
2    ['बड़े भूरे कुत्ते बाहर रेत में दौड़ रहे हैं।']   
3  ['कुत्ते बर्फ के बीच एक आदमी को एक प्रकार के स...   
4  ['फूलों के मैदान में बैठा एक धूसर कुर्ता पहना ...   

                                                   3  
0  ['सड़क पर घूमते हुए काले कपड़े पहने हुए एक महि...  
1        ['एक पुरुष और एक महिला कैमरा देख रही हैं।']  
2             ['एक भूरा कुत्ता गंदगी में दौड़ता है']  
3  ['तीन कुत्ते बर्फ के बीच एक आदमी को सायकल पर ख...  
4  ['एक लाल टोपी पहने हुए बच्चे जो स्ट्रोलर में ब...

In [4]:
df=df.head(16)

In [5]:
df.head(100)

0  \
0       Woman in a black dress walking on the street.   
1            A man and a woman looking at the camera.   
2   a brown dog running through the dirty muddy grass   
3   Three dogs pulling a man on a bicycle through ...   
4   A baby in a red hat sitting in a stroller is h...   
5   Three children playing with hay outdoors, thro...   
6   A climber is standing on the rock face next to...   
7   A black dog wearing an orange collar is entang...   
8            Two dogs are playing around in the dirt.   
9               A golden dog is running on the grass.   
10                      A dog runs through the grass.   
11  a man in red shorts is walking along rocks by ...   
12                                 Man rowing a boat.   
13                 Three dogs running on a racetrack.   
14  A black and brown dog walks through the snow n...   
15  A dog is jumping into a swimming pool after a ...   

                                                    1     2  \
0         A woman watches a dog jump down the stairs.  0.80   
1                         A man and a woman laughing.  2.33   
2   The large brown dog is running outside in the ...  3.60   
3   The dogs are pulling a man on a type of bike, ...  5.00   
4   A man in a gray shirt sitting in a field of fl...  0.00   
5   Three young children play in the hay, throwing...  4.80   
6   The children are running in the snow with fenc...  0.00   
7   The black dog wearing a red collar shakes wate...  1.80   
8   A dancer posing for the camera in a red and wh...  0.00   
9   The large beige dog is running through the grass.  3.40   
10                       a dog runs across the grass.  4.80   
11  A man is walking on rocks with water flowing a...  3.40   
12                  a man doing a trick on skateboard  0.00   
13            Three dogs round a bend at a racetrack.  4.80   
14  An older man stands outside a old boarded up b...  0.80   
15                A dog jumping into a swimming pool.  3.40   

                                                    4  \
0   ['एक महिला एक कुत्ता को सीढ़ियों से नीचे उछलने...   
1                  ['एक आदमी और एक औरत हंस रहे हैं।']   
2     ['बड़े भूरे कुत्ते बाहर रेत में दौड़ रहे हैं।']   
3   ['कुत्ते बर्फ के बीच एक आदमी को एक प्रकार के स...   
4   ['फूलों के मैदान में बैठा एक धूसर कुर्ता पहना ...   
5   ['तीन छोटे बच्चे घास में खेलते हैं और कुछ को क...   
6   ['बच्चे पीछे के पर्दे के साथ बर्फ में दौड़ रहे...   
7   ['लाल कोट पहने हुए काला कुत्ता पानी को हिलाने ...   
8   ['एक नर्तक जो लाल-श्वेत वस्त्र में कैमरा के लि...   
9            ['बड़ी बैज कुत्ता घास में दौड़ रही है।']   
10                  ['एक कुत्ता घास को पार करता है।']   
11  ['एक आदमी चट्टानों पर चल रहा है और उनके चारों ...   
12         ['एक आदमी स्कीटबोर्ड पर एक चाल कर रहा है']   
13  ['एक रेस ट्रैक पर तीन कुत्ते एक टेढ़ा पर घेरे ...   
14  ['एक वृद्ध आदमी एक पुरानी इमारत के बाहर खड़ा ह...   
15               ['एक कुत्ता एक तालाब में उछलता है।']   

                                                    3  
0   ['सड़क पर घूमते हुए काले कपड़े पहने हुए एक महि...  
1         ['एक पुरुष और एक महिला कैमरा देख रही हैं।']  
2              ['एक भूरा कुत्ता गंदगी में दौड़ता है']  
3   ['तीन कुत्ते बर्फ के बीच एक आदमी को सायकल पर ख...  
4   ['एक लाल टोपी पहने हुए बच्चे जो स्ट्रोलर में ब...  
5   ['तीन बच्चे बाहर घास के साथ खेलते हैं, कुछ को ...  
6   ['एक चढ़ने वाला गुलाबी रस्सी के बगल में चट्टान...  
7   ['एक नारंगी कॉलर पहने हुए काला कुत्ता मछली पकड...  
8               ['दो कुत्ते मिट्टी में खेल रहे हैं।']  
9           ['एक सोने का कुत्ता घास पर दौड़ रहा है।']  
10                   ['एक कुत्ता घास में दौड़ता है।']  
11  ['लाल कमर पहने हुए एक आदमी नदी के किनारे चट्टा...  
12                        ['नौका चलाने वाला मनुष्य।']  
13                         ['तीन कुत्ते दौड़ते हैं।']  
14  ['एक इमारत के पास एक काला और भूरा कुत्ता बर्फ ...  
15  ['एक मछली के बाद एक कुत्ता एक तालाब में कूद रह...

In [6]:
df=df.drop(columns=['1','0'])

In [7]:
stopwords_hi = ['तुम','मेरी','मुझे','क्योंकि','हम','प्रति','अबकी','आगे','माननीय','शहर','बताएं','कौनसी','क्लिक','किसकी','बड़े','मैं','and','रही','आज','लें','आपके','मिलकर','सब','मेरे','जी','श्री','वैसा','आपका','अंदर', 'अत', 'अपना', 'अपनी', 'अपने', 'अभी', 'आदि', 'आप', 'इत्यादि', 'इन', 'इनका', 'इन्हीं', 'इन्हें', 'इन्हों', 'इस', 'इसका', 'इसकी', 'इसके', 'इसमें', 'इसी', 'इसे', 'उन', 'उनका', 'उनकी', 'उनके', 'उनको', 'उन्हीं', 'उन्हें', 'उन्हों', 'उस', 'उसके', 'उसी', 'उसे', 'एक', 'एवं', 'एस', 'ऐसे', 'और', 'कई', 'कर','करता', 'करते', 'करना', 'करने', 'करें', 'कहते', 'कहा', 'का', 'काफ़ी', 'कि', 'कितना', 'किन्हें', 'किन्हों', 'किया', 'किर', 'किस', 'किसी', 'किसे', 'की', 'कुछ', 'कुल', 'के', 'को', 'कोई', 'कौन', 'कौनसा', 'गया', 'घर', 'जब', 'जहाँ', 'जा', 'जितना', 'जिन', 'जिन्हें', 'जिन्हों', 'जिस', 'जिसे', 'जीधर', 'जैसा', 'जैसे', 'जो', 'तक', 'तब', 'तरह', 'तिन', 'तिन्हें', 'तिन्हों', 'तिस', 'तिसे', 'तो', 'था', 'थी', 'थे', 'दबारा', 'दिया', 'दुसरा', 'दूसरे', 'दो', 'द्वारा', 'न', 'नहीं', 'ना', 'निहायत', 'नीचे', 'ने', 'पर', 'पर', 'पहले', 'पूरा', 'पे', 'फिर', 'बनी', 'बही', 'बहुत', 'बाद', 'बाला', 'बिलकुल', 'भी', 'भीतर', 'मगर', 'मानो', 'मे', 'में', 'यदि', 'यह', 'यहाँ', 'यही', 'या', 'यिह', 'ये', 'रखें', 'रहा', 'रहे', 'ऱ्वासा', 'लिए', 'लिये', 'लेकिन', 'व', 'वर्ग', 'वह', 'वह', 'वहाँ', 'वहीं', 'वाले', 'वुह', 'वे', 'वग़ैरह', 'संग', 'सकता', 'सकते', 'सबसे', 'सभी', 'साथ', 'साबुत', 'साभ', 'सारा', 'से', 'सो', 'ही', 'हुआ', 'हुई', 'हुए', 'है', 'हैं', 'हो', 'होता', 'होती', 'होते', 'होना', 'होने', 'अपनि', 'जेसे', 'होति', 'सभि', 'तिंहों', 'इंहों', 'दवारा', 'इसि', 'किंहें', 'थि', 'उंहों', 'ओर', 'जिंहें', 'वहिं', 'अभि', 'बनि', 'हि', 'उंहिं', 'उंहें', 'हें', 'वगेरह', 'एसे', 'रवासा', 'कोन', 'निचे', 'काफि', 'उसि', 'पुरा', 'भितर', 'हे', 'बहि', 'वहां', 'कोइ', 'यहां', 'जिंहों', 'तिंहें', 'किसि', 'कइ', 'यहि', 'इंहिं', 'जिधर', 'इंहें', 'अदि', 'इतयादि', 'हुइ', 'कोनसा', 'इसकि', 'दुसरे', 'जहां', 'अप', 'किंहों', 'उनकि', 'भि', 'वरग', 'हुअ', 'जेसा', 'नहिं']
punctuations = ['nn','n', '।','/', '`', '+', '\\', '"', '?', '▁(', '$', '@', '[', '_', "'", '!', ',', ':', '^', '|', ']', '=', '%', '&', '.', ')', '(', '#', '*', '', ';', '-', '}','|','"']

In [8]:
from indicnlp.tokenize import indic_tokenize
def tokenization(indic_string):
    tokens = []
    for t in indic_tokenize.trivial_tokenize(indic_string):
        tokens.append(t)
    return tokens


In [9]:
df.head()

2                                                  4  \
0  0.80  ['एक महिला एक कुत्ता को सीढ़ियों से नीचे उछलने...   
1  2.33                 ['एक आदमी और एक औरत हंस रहे हैं।']   
2  3.60    ['बड़े भूरे कुत्ते बाहर रेत में दौड़ रहे हैं।']   
3  5.00  ['कुत्ते बर्फ के बीच एक आदमी को एक प्रकार के स...   
4  0.00  ['फूलों के मैदान में बैठा एक धूसर कुर्ता पहना ...   

                                                   3  
0  ['सड़क पर घूमते हुए काले कपड़े पहने हुए एक महि...  
1        ['एक पुरुष और एक महिला कैमरा देख रही हैं।']  
2             ['एक भूरा कुत्ता गंदगी में दौड़ता है']  
3  ['तीन कुत्ते बर्फ के बीच एक आदमी को सायकल पर ख...  
4  ['एक लाल टोपी पहने हुए बच्चे जो स्ट्रोलर में ब...

In [10]:
df['3']=df['3'].apply(lambda x: tokenization(x))
df['4']=df['4'].apply(lambda x: tokenization(x))

In [11]:
to_be_removed = stopwords_hi + punctuations 


In [12]:
for i in range(len(df)):
    mask = df['3'].apply(lambda x: x not in to_be_removed)
    df.loc[mask, '3'] = df.loc[mask, '3'].apply(lambda x: [ele for ele in x if ele not in to_be_removed])

df.tail(10)

2                                                  4  \
6   0.0  [[, ', बच्चे, पीछे, के, पर्दे, के, साथ, बर्फ, ...   
7   1.8  [[, ', लाल, कोट, पहने, हुए, काला, कुत्ता, पानी...   
8   0.0  [[, ', एक, नर्तक, जो, लाल, -, श्वेत, वस्त्र, म...   
9   3.4  [[, ', बड़ी, बैज, कुत्ता, घास, में, दौड़, रही,...   
10  4.8  [[, ', एक, कुत्ता, घास, को, पार, करता, है, ।, ...   
11  3.4  [[, ', एक, आदमी, चट्टानों, पर, चल, रहा, है, और...   
12  0.0  [[, ', एक, आदमी, स्कीटबोर्ड, पर, एक, चाल, कर, ...   
13  4.8  [[, ', एक, रेस, ट्रैक, पर, तीन, कुत्ते, एक, टे...   
14  0.8  [[, ', एक, वृद्ध, आदमी, एक, पुरानी, इमारत, के,...   
15  3.4  [[, ', एक, कुत्ता, एक, तालाब, में, उछलता, है, ...   

                                                    3  
6     [चढ़ने, वाला, गुलाबी, रस्सी, बगल, चट्टान, खड़ा]  
7   [नारंगी, कॉलर, पहने, काला, कुत्ता, मछली, पकड़न...  
8                               [कुत्ते, मिट्टी, खेल]  
9                           [सोने, कुत्ता, घास, दौड़]  
10                              [कुत्ता, घास, दौड़ता]  
11  [लाल, कमर, पहने, आदमी, नदी, किनारे, चट्टानों, ...  
12                        [नौका, चलाने, वाला, मनुष्य]  
13                              [तीन, कुत्ते, दौड़ते]  
14  [इमारत, पास, काला, भूरा, कुत्ता, बर्फ, बीच, चलता]  
15                         [मछली, कुत्ता, तालाब, कूद]

In [13]:
for i in range(len(df)):
    mask = df['4'].apply(lambda x: x not in to_be_removed)
    df.loc[mask, '4'] = df.loc[mask, '4'].apply(lambda x: [ele for ele in x if ele not in to_be_removed])

df.tail(10)

2                                                  4  \
6   0.0                   [बच्चे, पीछे, पर्दे, बर्फ, दौड़]   
7   1.8  [लाल, कोट, पहने, काला, कुत्ता, पानी, हिलाने, ल...   
8   0.0     [नर्तक, लाल, श्वेत, वस्त्र, कैमरा, पोशाक, बना]   
9   3.4                     [बड़ी, बैज, कुत्ता, घास, दौड़]   
10  4.8                                 [कुत्ता, घास, पार]   
11  3.4              [आदमी, चट्टानों, चल, चारों, पानी, बह]   
12  0.0                            [आदमी, स्कीटबोर्ड, चाल]   
13  4.8       [रेस, ट्रैक, तीन, कुत्ते, टेढ़ा, घेरे, रहते]   
14  0.8           [वृद्ध, आदमी, पुरानी, इमारत, बाहर, खड़ा]   
15  3.4                             [कुत्ता, तालाब, उछलता]   

                                                    3  
6     [चढ़ने, वाला, गुलाबी, रस्सी, बगल, चट्टान, खड़ा]  
7   [नारंगी, कॉलर, पहने, काला, कुत्ता, मछली, पकड़न...  
8                               [कुत्ते, मिट्टी, खेल]  
9                           [सोने, कुत्ता, घास, दौड़]  
10                              [कुत्ता, घास, दौड़ता]  
11  [लाल, कमर, पहने, आदमी, नदी, किनारे, चट्टानों, ...  
12                        [नौका, चलाने, वाला, मनुष्य]  
13                              [तीन, कुत्ते, दौड़ते]  
14  [इमारत, पास, काला, भूरा, कुत्ता, बर्फ, बीच, चलता]  
15                         [मछली, कुत्ता, तालाब, कूद]

In [14]:
def joining(lixt):
    return " ".join(lixt)

In [15]:
df['5']=df['3'].apply(joining)
df['6']=df['4'].apply(joining)

In [227]:
from transformers import AutoModel, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('ai4bharat/indic-bert')

model = AutoModel.from_pretrained('ai4bharat/indic-bert')

In [228]:
def word_em(text):    
    encoded_input = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
    word_embeddings = model(**encoded_input).last_hidden_state
    sentence_embedding = word_embeddings.mean(dim=1)
    return sentence_embedding

In [229]:
df['5']=df['5'].apply(word_em)
df['6']=df['6'].apply(word_em)

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.


In [13]:
df.head()

2                                                4  \
0  0.80          [महिला, कुत्ता, सीढ़ियों, उछलने, देखती]   
1  2.33                                 [आदमी, औरत, हंस]   
2  3.60            [बड़े, भूरे, कुत्ते, बाहर, रेत, दौड़]   
3  5.00  [कुत्ते, बर्फ, बीच, आदमी, प्रकार, साइकिल, खींच]   
4  0.00   [फूलों, मैदान, बैठा, धूसर, कुर्ता, पहना, आदमी]   

                                                   3  \
0            [सड़क, घूमते, काले, कपड़े, पहने, महिला]   
1                         [पुरुष, महिला, कैमरा, देख]   
2                      [भूरा, कुत्ता, गंदगी, दौड़ता]   
3      [तीन, कुत्ते, बर्फ, बीच, आदमी, सायकल, खींचते]   
4  [लाल, टोपी, पहने, बच्चे, स्ट्रोलर, बैठा, पुतली...   

                                              5  \
0              सड़क घूमते काले कपड़े पहने महिला   
1                         पुरुष महिला कैमरा देख   
2                      भूरा कुत्ता गंदगी दौड़ता   
3         तीन कुत्ते बर्फ बीच आदमी सायकल खींचते   
4  लाल टोपी पहने बच्चे स्ट्रोलर बैठा पुतली पकड़   

                                         6  
0        महिला कुत्ता सीढ़ियों उछलने देखती  
1                             आदमी औरत हंस  
2           बड़े भूरे कुत्ते बाहर रेत दौड़  
3  कुत्ते बर्फ बीच आदमी प्रकार साइकिल खींच  
4   फूलों मैदान बैठा धूसर कुर्ता पहना आदमी

In [16]:
from sklearn.preprocessing import MinMaxScaler
# Create a scaler object
scaler = MinMaxScaler()
# Fit the scaler to the 'similarity_score' column and transform it
df['2'] = scaler.fit_transform(df[['2']])

In [232]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np

class SiameseNetwork(nn.Module):
    def __init__(self):
        super(SiameseNetwork, self).__init__()
        self.fc1 = nn.Linear(768, 128) 
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 32)
        self.fc4 = nn.Linear(32, 1)

    def forward_once(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        x = torch.relu(self.fc3(x))
        x = torch.sigmoid(self.fc4(x))
        return x

    def forward(self, input1, input2):
        output1 = self.forward_once(input1)
        output2 = self.forward_once(input2)
        return output1, output2





In [233]:
from sklearn.model_selection import train_test_split
import ast


embeddings_5 = torch.stack([torch.tensor(x) for x in df['5']])
embeddings_6 = torch.stack([torch.tensor(x) for x in df['6']])

X = torch.stack([embeddings_5, embeddings_6], dim=2).squeeze()
y=torch.tensor(df['2'])
criterion = nn.MSELoss()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

input1 = X_train[0]  
input2 = X_train[1] 
target_scores = y_train  

C:\Users\Gaurav B V\AppData\Local\Temp\ipykernel_31796\1077647096.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  embeddings_5 = torch.stack([torch.tensor(x) for x in df['5']])
C:\Users\Gaurav B V\AppData\Local\Temp\ipykernel_31796\1077647096.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  embeddings_6 = torch.stack([torch.tensor(x) for x in df['6']])


In [234]:
embeddings_5.shape, embeddings_6.shape, X.shape, y.shape

(torch.Size([16, 1, 768]),
 torch.Size([16, 1, 768]),
 torch.Size([16, 2, 768]),
 torch.Size([16]))

In [235]:
X_train.shape

torch.Size([12, 2, 768])

In [236]:
input2.shape, input1.shape

(torch.Size([2, 768]), torch.Size([2, 768]))

In [237]:
model = SiameseNetwork()
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [238]:
from torch.nn.functional import pairwise_distance


In [239]:
from torch.utils.data import DataLoader

train_loader = DataLoader(X_train, batch_size=32, shuffle=True)
count = 0
for i,lol in enumerate(X_train):
    print(lol)
print(count)

tensor([[ 0.0963, -0.3063, -0.1304,  ...,  0.1736, -0.0420, -0.1476],
        [ 0.1713, -0.2558, -0.2464,  ...,  0.1953, -0.0466, -0.1717]])
tensor([[ 0.0988, -0.2796, -0.2124,  ...,  0.1832,  0.1292,  0.0462],
        [ 0.1601, -0.1882, -0.0406,  ...,  0.1208,  0.1845, -0.1601]])
tensor([[ 0.1084, -0.2348, -0.0841,  ...,  0.0777, -0.0937, -0.1194],
        [-0.1087, -0.4634, -0.0564,  ...,  0.2898, -0.1195, -0.1173]])
tensor([[-0.0395, -0.4326, -0.1059,  ...,  0.0857, -0.0731,  0.0271],
        [ 0.0624, -0.3882, -0.1599,  ...,  0.0955, -0.1546, -0.0605]])
tensor([[ 0.2829, -0.2057, -0.0168,  ...,  0.1548, -0.0643, -0.1450],
        [ 0.2920, -0.3614, -0.1285,  ...,  0.1376, -0.0536, -0.1281]])
tensor([[ 0.3293, -0.0334,  0.0703,  ...,  0.1034, -0.1490, -0.0623],
        [ 0.2789, -0.1222, -0.0839,  ...,  0.1439, -0.1046, -0.0346]])
tensor([[ 0.0699, -0.3359, -0.1597,  ...,  0.1708,  0.0166, -0.1011],
        [ 0.0499, -0.1870, -0.0303,  ...,  0.1038,  0.2377, -0.1658]])
tensor([[ 0.1

In [291]:
from torch.utils.data import DataLoader

# Assuming train_dataset is your training dataset
train_loader = DataLoader(X_train, batch_size=32, shuffle=True)

num_epochs = 20
margin = 1.0  # Define your margin here

for epoch in range(num_epochs):
    for i in enumerate(train_loader):
        model.train()
        optimizer.zero_grad()
        output1, output2 = model(input1, input2)
        
        # Calculate Euclidean distance between output1 and output2
        euclidean_distance = pairwise_distance(output1, output2)
        
        # Define contrastive loss
        loss_contrastive = torch.mean((1) * torch.pow(euclidean_distance, 2) +
                                      (1) * torch.pow(torch.clamp(margin - euclidean_distance, min=0.0), 2))
        
        loss_contrastive.backward()
        optimizer.step()
        
    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss_contrastive.item()}')

Epoch [1/20], Loss: 0.5
Epoch [2/20], Loss: 0.5
Epoch [3/20], Loss: 0.5
Epoch [4/20], Loss: 0.5
Epoch [5/20], Loss: 0.5
Epoch [6/20], Loss: 0.5
Epoch [7/20], Loss: 0.5
Epoch [8/20], Loss: 0.5
Epoch [9/20], Loss: 0.5
Epoch [10/20], Loss: 0.5
Epoch [11/20], Loss: 0.5
Epoch [12/20], Loss: 0.5
Epoch [13/20], Loss: 0.5
Epoch [14/20], Loss: 0.5
Epoch [15/20], Loss: 0.5
Epoch [16/20], Loss: 0.5
Epoch [17/20], Loss: 0.5
Epoch [18/20], Loss: 0.5
Epoch [19/20], Loss: 0.5
Epoch [20/20], Loss: 0.5


In [15]:
df.head()

2                                                4  \
0  0.160          [महिला, कुत्ता, सीढ़ियों, उछलने, देखती]   
1  0.466                                 [आदमी, औरत, हंस]   
2  0.720            [बड़े, भूरे, कुत्ते, बाहर, रेत, दौड़]   
3  1.000  [कुत्ते, बर्फ, बीच, आदमी, प्रकार, साइकिल, खींच]   
4  0.000   [फूलों, मैदान, बैठा, धूसर, कुर्ता, पहना, आदमी]   

                                                   3  \
0            [सड़क, घूमते, काले, कपड़े, पहने, महिला]   
1                         [पुरुष, महिला, कैमरा, देख]   
2                      [भूरा, कुत्ता, गंदगी, दौड़ता]   
3      [तीन, कुत्ते, बर्फ, बीच, आदमी, सायकल, खींचते]   
4  [लाल, टोपी, पहने, बच्चे, स्ट्रोलर, बैठा, पुतली...   

                                              5  \
0              सड़क घूमते काले कपड़े पहने महिला   
1                         पुरुष महिला कैमरा देख   
2                      भूरा कुत्ता गंदगी दौड़ता   
3         तीन कुत्ते बर्फ बीच आदमी सायकल खींचते   
4  लाल टोपी पहने बच्चे स्ट्रोलर बैठा पुतली पकड़   

                                         6  
0        महिला कुत्ता सीढ़ियों उछलने देखती  
1                             आदमी औरत हंस  
2           बड़े भूरे कुत्ते बाहर रेत दौड़  
3  कुत्ते बर्फ बीच आदमी प्रकार साइकिल खींच  
4   फूलों मैदान बैठा धूसर कुर्ता पहना आदमी

In [208]:
df["4"].tolist()

[['महिला', 'कुत्ता', 'सीढ़ियों', 'उछलने', 'देखती'],
 ['आदमी', 'औरत', 'हंस'],
 ['बड़े', 'भूरे', 'कुत्ते', 'बाहर', 'रेत', 'दौड़'],
 ['कुत्ते', 'बर्फ', 'बीच', 'आदमी', 'प्रकार', 'साइकिल', 'खींच'],
 ['फूलों', 'मैदान', 'बैठा', 'धूसर', 'कुर्ता', 'पहना', 'आदमी'],
 ['तीन', 'छोटे', 'बच्चे', 'घास', 'खेलते', 'कैमरा', 'फेंकते'],
 ['बच्चे', 'पीछे', 'पर्दे', 'बर्फ', 'दौड़'],
 ['लाल', 'कोट', 'पहने', 'काला', 'कुत्ता', 'पानी', 'हिलाने', 'लगता'],
 ['नर्तक', 'लाल', 'श्वेत', 'वस्त्र', 'कैमरा', 'पोशाक', 'बना'],
 ['बड़ी', 'बैज', 'कुत्ता', 'घास', 'दौड़'],
 ['कुत्ता', 'घास', 'पार'],
 ['आदमी', 'चट्टानों', 'चल', 'चारों', 'पानी', 'बह'],
 ['आदमी', 'स्कीटबोर्ड', 'चाल'],
 ['रेस', 'ट्रैक', 'तीन', 'कुत्ते', 'टेढ़ा', 'घेरे', 'रहते'],
 ['वृद्ध', 'आदमी', 'पुरानी', 'इमारत', 'बाहर', 'खड़ा'],
 ['कुत्ता', 'तालाब', 'उछलता']]

In [18]:
df['7']=df['5'].apply(hindi_stemming)
df['8']=df['6'].apply(hindi_stemming)

In [19]:
import torch
from transformers import DistilBertModel, DistilBertTokenizer
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
import numpy as np

class SimilarityDataset(Dataset):
    def __init__(self, sentences1, sentences2, similarity_scores, tokenizer):
        self.sentences1 = sentences1
        self.sentences2 = sentences2
        self.similarity_scores = similarity_scores
        self.tokenizer = tokenizer

    def __len__(self):
        return len(self.sentences1)

    def __getitem__(self, idx):
        sentence1 = self.sentences1[idx]
        sentence2 = self.sentences2[idx]
        similarity_score = self.similarity_scores[idx]

        encoding = self.tokenizer(sentence1, sentence2, return_tensors='pt', padding=True, truncation=True)
        input_ids = encoding['input_ids']
        attention_mask = encoding['attention_mask']

        return {
            'input_ids': input_ids,
            'attention_mask': attention_mask,
            'similarity_score': torch.tensor(similarity_score, dtype=torch.float32)
        }

# Instantiate the BERT model and tokenizer
tokenizer = DistilBertTokenizer.from_pretrained('distilbert-base-uncased')
model = DistilBertModel.from_pretrained('distilbert-base-uncased')

# Freeze BERT parameters
for param in model.parameters():
    param.requires_grad = False

# Define regression head on top of BERT
class RegressionHead(nn.Module):
    def __init__(self):
        super(RegressionHead, self).__init__()
        self.linear1 = nn.Linear(768, 256)
        self.linear2 = nn.Linear(256, 1)

    def forward(self, x):
        x = torch.relu(self.linear1(x))
        x = self.linear2(x)
        return x

# Instantiate the regression head
regression_head = RegressionHead()

# Define your dataset and dataloader
sentences1 = df['7'].tolist()  # List of first sentences
sentences2 = df['8'].tolist()  # List of second sentences
similarity_scores = df['2'].tolist()  # List of similarity scores
dataset = SimilarityDataset(sentences1, sentences2, similarity_scores, tokenizer)
dataloader = DataLoader(dataset, batch_size=1, shuffle=True)

# Define loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(regression_head.parameters(), lr=1e-4)




c:\g\pproject\aimbot\bot\bot\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [210]:
df['3'].tolist()

[['सड़क', 'घूमते', 'काले', 'कपड़े', 'पहने', 'महिला'],
 ['पुरुष', 'महिला', 'कैमरा', 'देख'],
 ['भूरा', 'कुत्ता', 'गंदगी', 'दौड़ता'],
 ['तीन', 'कुत्ते', 'बर्फ', 'बीच', 'आदमी', 'सायकल', 'खींचते'],
 ['लाल', 'टोपी', 'पहने', 'बच्चे', 'स्ट्रोलर', 'बैठा', 'पुतली', 'पकड़'],
 ['तीन', 'बच्चे', 'बाहर', 'घास', 'खेलते', 'कैमरा', 'लेंस', 'फेंकते'],
 ['चढ़ने', 'वाला', 'गुलाबी', 'रस्सी', 'बगल', 'चट्टान', 'खड़ा'],
 ['नारंगी', 'कॉलर', 'पहने', 'काला', 'कुत्ता', 'मछली', 'पकड़ने', 'तार', 'फंसा'],
 ['कुत्ते', 'मिट्टी', 'खेल'],
 ['सोने', 'कुत्ता', 'घास', 'दौड़'],
 ['कुत्ता', 'घास', 'दौड़ता'],
 ['लाल',
  'कमर',
  'पहने',
  'आदमी',
  'नदी',
  'किनारे',
  'चट्टानों',
  'चिड़ी',
  'लेकर',
  'चल'],
 ['नौका', 'चलाने', 'वाला', 'मनुष्य'],
 ['तीन', 'कुत्ते', 'दौड़ते'],
 ['इमारत', 'पास', 'काला', 'भूरा', 'कुत्ता', 'बर्फ', 'बीच', 'चलता'],
 ['मछली', 'कुत्ता', 'तालाब', 'कूद']]

In [27]:
dataloader.dataset[0]

{'input_ids': tensor([[  101,  1338, 29857, 29851,   100,  1315, 29876, 29870,  1315, 29864,
          29857,  1328, 29875,  1331, 29875, 29877, 29870,   102,  1331, 29875,
          29877, 29870,  1315, 29859, 29859,   100,   100,  1325, 29852,   102]]),
 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
          1, 1, 1, 1, 1, 1]]),
 'similarity_score': tensor(0.1600)}

In [180]:
df.shape

(16, 3)

In [17]:
from snowballstemmer import stemmer

def hindi_stemming(text):
    stemmer_obj = stemmer("hindi")
    
    words = text.split()
    
    stemmed_words = []
    for word in words:
        stemmed_word = stemmer_obj.stemWord(word)
        stemmed_words.append(stemmed_word)
    
    stemmed_text = ' '.join(stemmed_words)
    
    return stemmed_text

input_text = "तीन, कुत्ते, बर्फ, बीच, आदमी, सायकल, खींचते"
stemmed_text = hindi_stemming(input_text)
print("Stemmed Text:", stemmed_text)


Stemmed Text: तीन, कुत्ते, बर्फ, बीच, आदमी, सायकल, खींच


In [25]:
df.head()

2                                                4  \
0  0.160          [महिला, कुत्ता, सीढ़ियों, उछलने, देखती]   
1  0.466                                 [आदमी, औरत, हंस]   
2  0.720            [बड़े, भूरे, कुत्ते, बाहर, रेत, दौड़]   
3  1.000  [कुत्ते, बर्फ, बीच, आदमी, प्रकार, साइकिल, खींच]   
4  0.000   [फूलों, मैदान, बैठा, धूसर, कुर्ता, पहना, आदमी]   

                                                   3  \
0            [सड़क, घूमते, काले, कपड़े, पहने, महिला]   
1                         [पुरुष, महिला, कैमरा, देख]   
2                      [भूरा, कुत्ता, गंदगी, दौड़ता]   
3      [तीन, कुत्ते, बर्फ, बीच, आदमी, सायकल, खींचते]   
4  [लाल, टोपी, पहने, बच्चे, स्ट्रोलर, बैठा, पुतली...   

                                              5  \
0              सड़क घूमते काले कपड़े पहने महिला   
1                         पुरुष महिला कैमरा देख   
2                      भूरा कुत्ता गंदगी दौड़ता   
3         तीन कुत्ते बर्फ बीच आदमी सायकल खींचते   
4  लाल टोपी पहने बच्चे स्ट्रोलर बैठा पुतली पकड़   

                                         6  \
0        महिला कुत्ता सीढ़ियों उछलने देखती   
1                             आदमी औरत हंस   
2           बड़े भूरे कुत्ते बाहर रेत दौड़   
3  कुत्ते बर्फ बीच आदमी प्रकार साइकिल खींच   
4   फूलों मैदान बैठा धूसर कुर्ता पहना आदमी   

                                        7  \
0               सड़क घूम काल कपड़ पह महिल   
1                     पुरुष महिल कैमर देख   
2                     भूर कुत्त गंदग दौड़   
3       तीन कुत्त बर्फ बीच आदम सायकल खींच   
4  लाल टोप पह बच्च स्ट्रोलर बैठ पुतल पकड़   

                                       8  
0                महिल कुत्त सीढ़ उछल देख  
1                            आदम औरत हंस  
2            बड़ भूर कुत्त बाहर रेत दौड़  
3  कुत्त बर्फ बीच आदम प्रकार साइकिल खींच  
4        फूल मैदान बैठ धूसर कुर्त पह आदम

In [29]:
# Training loop
num_epochs = 10
for epoch in range(num_epochs):
    total_loss = 0
    for batch in dataloader:
        input_ids = batch['input_ids'].squeeze(1)
        attention_mask = batch['attention_mask'].squeeze(1)
        similarity_scores = batch['similarity_score'].unsqueeze(-1)

        # Forward pass
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.last_hidden_state[:, 0, :]  # Take the first token's output as sentence embedding
        predicted_scores = regression_head(pooled_output)

        # Compute loss
        loss = criterion(predicted_scores, similarity_scores)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch + 1}, Loss: {total_loss / len(dataloader)}")

# Evaluate your model on a validation set if available

Epoch 1, Loss: 0.0583471949168024
Epoch 2, Loss: 0.05721338993043901
Epoch 3, Loss: 0.06020940892744875
Epoch 4, Loss: 0.05120053639257094
Epoch 5, Loss: 0.048969033533467154
Epoch 6, Loss: 0.04757164392575319
Epoch 7, Loss: 0.04550043505298618
Epoch 8, Loss: 0.04787069118151521
Epoch 9, Loss: 0.04315972066882523
Epoch 10, Loss: 0.04245049664586986


In [28]:
model.eval()

DistilBertModel(
  (embeddings): Embeddings(
    (word_embeddings): Embedding(30522, 768, padding_idx=0)
    (position_embeddings): Embedding(512, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (transformer): Transformer(
    (layer): ModuleList(
      (0-5): 6 x TransformerBlock(
        (attention): MultiHeadSelfAttention(
          (dropout): Dropout(p=0.1, inplace=False)
          (q_lin): Linear(in_features=768, out_features=768, bias=True)
          (k_lin): Linear(in_features=768, out_features=768, bias=True)
          (v_lin): Linear(in_features=768, out_features=768, bias=True)
          (out_lin): Linear(in_features=768, out_features=768, bias=True)
        )
        (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        (ffn): FFN(
          (dropout): Dropout(p=0.1, inplace=False)
          (lin1): Linear(in_features=768, out_features=3072, bias=True)
          (lin2): Li

In [27]:
# Pair of sentences
new_input = {
    'sentence1': 'पुरुष महिला कैमरा देख',
    'sentence2': 'तीन कुत्ते बर्फ बीच आदमी सायकल खींचते'
}

# Tokenize the pair of sentences
inputs = tokenizer(new_input['sentence1'], new_input['sentence2'], return_tensors='pt')

# Extract tensors
input_ids = inputs['input_ids']
attention_mask = inputs['attention_mask']

# Pass the tensors to the model
outputs = model(input_ids=input_ids, attention_mask=attention_mask)

# Extract the last hidden state
pooled_output = outputs.last_hidden_state[:, 0, :]

# Pass the pooled output to the regression head
predicted_scores = regression_head(pooled_output)

# The predicted score is the first element of `predicted_scores`
predicted_score = predicted_scores[0].item()

print(f"The predicted similarity score for the new input is {predicted_score}")

The predicted similarity score for the new input is 0.5435514450073242


In [64]:
df.head()

2                                                  4  \
0  0.80  ['एक महिला एक कुत्ता को सीढ़ियों से नीचे उछलने...   
1  2.33                 ['एक आदमी और एक औरत हंस रहे हैं।']   
2  3.60    ['बड़े भूरे कुत्ते बाहर रेत में दौड़ रहे हैं।']   
3  5.00  ['कुत्ते बर्फ के बीच एक आदमी को एक प्रकार के स...   
4  0.00  ['फूलों के मैदान में बैठा एक धूसर कुर्ता पहना ...   

                                                   3  
0  ['सड़क पर घूमते हुए काले कपड़े पहने हुए एक महि...  
1        ['एक पुरुष और एक महिला कैमरा देख रही हैं।']  
2             ['एक भूरा कुत्ता गंदगी में दौड़ता है']  
3  ['तीन कुत्ते बर्फ के बीच एक आदमी को सायकल पर ख...  
4  ['एक लाल टोपी पहने हुए बच्चे जो स्ट्रोलर में ब...

In [1]:
# Pair of sentences
new_input = {
    'sentence1': 'The cat sat on the mat.',
    'sentence2': 'A cat is sitting on the mat.'
}

# Tokenize the pair of sentences
inputs = tokenizer(new_input['sentence1'], new_input['sentence2'], return_tensors='pt')

# Extract tensors
input_ids = inputs['input_ids']
attention_mask = inputs['attention_mask']

# Pass the tensors to the model
outputs = model(input_ids=input_ids, attention_mask=attention_mask)

# Extract the last hidden state
pooled_output = outputs.last_hidden_state[:, 0, :]

# Pass the pooled output to the regression head
predicted_scores = regression_head(pooled_output)

# The predicted score is the first element of `predicted_scores`
predicted_score = predicted_scores[0].item()

print(f"The predicted similarity score for the new input is {predicted_score}")

NameError: name 'tokenizer' is not defined